### ISSUE TITLE
CPU Usage

### ISSUE THREAD

**Issue by timothyghanim** [sipsorcery/SIPSorceryMedia.Encoders#1]
I am working on a media streaming client that streams two screens (1920x1080) and 1 camera (640x480).

I noticed that the Vpx encoder consumes a lot of CPU (~50%) which for me is reasonable because I have 3 video streams that are being encoded.

My question is: is there a way I can control the CPU utilization? I expect that the encoder might become significantly slower but at least a setting that will help me fine-tune it.

**Comment by sipsorcery** [comment]
There are a few things you could try:

- The VP8 codec has lots of options. You could check out the docs and try tweaking them in the [codec initialiation method](https://github.com/sipsorcery-org/SIPSorceryMedia.Encoders/blob/85d11ec7c79b819f0ab76961327d2b5487ebbfdf/src/codecs/Vp8Codec.cs#L65).

- Reducing the frame rate and/or resolution is likely to have a BIG impact on CPU. I suspect you're already probably down to 5 fps, given you're using a 1080p stream, but if you can live with 1fps or less that would be a big reduction in CPU.

- Last one is more of a warning rather than option. This library sacrifices performance for usability when it transfers video frames across the native to managed boundary. The cost of working with video frames in dotnet is high CPU. You might be able to reduce it a bit with options like the previous two, but eventually, if you need a greater reduction, the answer is C++.
